### ISSUE TITLE
HTML and XML rendering functions don't yet exist

### ISSUE THREAD

**Issue by waldoj** [project-open-data/db-to-api#1]
DB_API has the following two functions:

``` php

function render_html( $data ) {

    var_dump( $data );
}


function render_xml( $data ) {

    echo "XML HERE";

}
```

These two functions need to actually perform the advertised tasks.

**Comment by benbalter** [comment]
The PHP Object to XML logic lives in the GSA digital strategy report
generator and can be adopted with a light lift.

For HTML, I was just going to loop a spit out a table. Glad to tackle, or
your more then welcome to if you have time.

On Sep 27, 2012, at 9:37 AM, Waldo Jaquith notifications@github.com wrote:

DB_API has the following two functions:

function render_html( $data ) {

```
var_dump( $data );}
```

function render_xml( $data ) {

```
echo "XML HERE";
```

}

These two functions need to actually perform the advertised tasks.

—
Reply to this email directly or view it on
GitHubhttps://github.com/project-open-data/db-to-api/issues/1.
