### ISSUE TITLE
Auth Keys

### ISSUE THREAD

**Issue by nomadicjosh** [project-open-data/db-to-api#11]
I am new to RESTful API. How would I go about adding an authentication key for making this a private RESTful API?

**Comment by benbalter** [comment]
You'll most likely want to implement Oauth. You can take a look at [GitHub's developer documentation](http://developer.github.com/v3/oauth/) as an example of what that flow might look like.

**Comment by waldoj** [comment]
Also, there are two very easy ways, if you want to provide only a very small number of keys that you'll manage.

The first is to add a very crude key right into `index.php`, right after the `include` stanzas complete, a little like this:

``` php
if (!isset($_GET['key']) || ($_GET['key'] != 'My Secret Password'])
{
   die('Valid key required.');
}
```

The second is to add a few lines to `.htaccess` to [require authentication at the web server level](http://httpd.apache.org/docs/2.2/howto/auth.html), assuming that your clients are sophisticated enough to be able to provide an HTTP username and password.

Oauth is the _right_ way to solve this, but if your needs are basic enough, these will do the trick, too.

**Comment by nomadicjosh** [comment]
Ok, thanks.
