### ISSUE TITLE
Abstract the PDO connection

### ISSUE THREAD

**Issue by waldoj** [project-open-data/db-to-api#2]
The PDO connection is being made like such:

``` php
new PDO("mysql:host={$db->server};dbname={$db->name}", $db->username, $db->password );
```

This is obviously not database agnostic, as it needs to be.

**Comment by waldoj** [comment]
It looks like every database will need its own DSN. Here is the relevant documentation for each, which includes sample DSNs:
- [CUBRID](http://php.net/manual/en/ref.pdo-cubrid.connection.php)
- [Firebird/Interbase](http://php.net/manual/en/ref.pdo-firebird.connection.php)
- [IBM](http://php.net/manual/en/ref.pdo-ibm.connection.php)
- [Informix](http://php.net/manual/en/ref.pdo-informix.connection.php)
- [MySQL](http://php.net/manual/en/ref.pdo-mysql.connection.php)
- [MS SQL Server](http://php.net/manual/en/ref.pdo-sqlsrv.php)
- [Oracle](http://php.net/manual/en/ref.pdo-oci.php)
- [ODBC and DB2](http://php.net/manual/en/ref.pdo-odbc.connection.php)
- [PostgreSQL](http://php.net/manual/en/ref.pdo-pgsql.connection.php)
- [SQLite](http://php.net/manual/en/ref.pdo-sqlite.connection.php)
- [4D](http://php.net/manual/en/ref.pdo-4d.connection.php)

**Comment by waldoj** [comment]
The defaults include a standard port of 3306. Note that is MySQL's default port, and we'll only want to use as the default if the specified database is MySQL. If it is not, that would prevent any other database from working. Either devise a simple method of storing an appropriate default port for each database or eliminate the default port entirely.

**Comment by waldoj** [comment]
All of these are now (theoretically) supported, _except for Oracle_. That's non-trivial to implement, so I skipped it for the moment.

**Comment by waldoj** [comment]
I forgot to update this ~11 days ago to point out that Oracle support is now included.

But it remains to deal with the default ports problem.

**Comment by benbalter** [comment]
props again.
