### ISSUE TITLE
All errors currently echo'd should be using the `error()` function

### ISSUE THREAD

**Issue by benbalter** [project-open-data/db-to-api#7]
e.g., https://github.com/project-open-data/db-to-api/blob/master/includes/class.db-api.php#L234.

This does three things: 

1) it will return the proper error code
2) it will halt the script from running
3) It will allow us to do better error handling (e.g., logging) in the long run.

Rather than `echo "msg"` as is now, would just need to be moved to `$this->error( $msg );`

**Comment by waldoj** [comment]
I'm really bad about this. :( It's a 13-year-old habit that I've really got to break.
